### ISSUE TITLE
Handling cards

### ISSUE THREAD

**Issue by KimNorgaard** [sinkingpoint/GHC-Errbot#6]
See https://github.com/KimNorgaard/GHC-Errbot/commit/9ada23f737f1b96315b041177210a701caae1ff0

This covers being able to send cards through the backend plugin directly like this:

```python
@botcmd
def my_cmd(self, msg, args):
    cards = [{'sections': [{'widgets': []}]}]  # etc...
    self._bot.send_card(cards=cards, space_id=msg.extras['space_id'], thread_id=msg.extras['thread_id'])
```

I can create a PR for this if you want me to.

The other way around (handling CARD_CLICKED events) is a bit more tricky as it involves somehow making the bot commands aware that the message isn't just plain text. This could be achieved by passing the event data in the Message.extras attribute and reserving commands for handling these events, e.g.

In `hangouts_chat.py` - `GoogleHangoutsChatBackend._handle_message()`:
```python
    if data['type'] == 'CARD_CLICKED':
        msg.body = 'handle ghc clicked'
        msg.extras['card_event'] = data
```

In the bot plugin:
```python
@botcmd
def handle_ghc_card_clicked(self, msg, args):
    msg.extras['card_event']  # { "type": "CARD_CLICKED", "message":{ ...
```

Any thoughts on this?

**Comment by sinkingpoint** [comment]
I've had a bit of a think about this. What if we did some `type` magic in the send_message function? I'd like to keep the idiomatic "`return/yield` to send a message" as much as possible, so I'm not entirely comfortable with exposing methods on the _bot object to plugins. 

Basically what I'm suggesting for the sending cards usecase, is something like the following at https://github.com/sinkingpoint/GHC-Errbot/blob/master/hangouts_chat.py#L253-L255 (I'll type this up properly with a working commit later)

```python
if type(message.body) == dict:
  #We're sending a card
  message_payload = {
    'cards': [message.body]
  }
elif type(message.body) == list:
  #We're sending multiple cards
  message_payload = {
    'cards': message.body
  }
else:
  # We're sending a text message
  message_payload = {
    'text': message.body
  }
```

**Comment by sinkingpoint** [comment]
As to "CARD_CLICKED" events, I haven't really played around with them. Would they even be possible in errbot? What do we get as a body to that call? - Basically, I'm not sure now errbots matching to find the function to call would work

**Comment by sinkingpoint** [comment]
Ah. You're right :/ I think we're stuck between a rock and a hard place in that instance then. I agree that your solution is probably cleanest
